### ISSUE TITLE
All genomic locations are off by 1 in all organisms (leftpos too low)

### ISSUE THREAD

**Issue by jlerman44** [SBRG/cobradb#45]
select * from genome_region where bigg_id = 'b0007';
id | chromosome_id | bigg_id | leftpos | rightpos | strand | type
-------+---------------+---------+---------+----------+--------+------
91862 | 91798 | b0007 | 6528 | 7959 | - | gene

https://ecocyc.org/gene?orgid=ECOLI&id=EG11555
[6,529 <- 7,959] (0.14 centisomes, 1°)

ME-Model code would've caught this easy ;).

**Comment by zakandrewking** [comment]
thanks for making the PR 👍
